### ISSUE TITLE
希望适配下华为屏（2160*1440）

### ISSUE THREAD

**Issue by Dr-Vibia** [SkeathyTomas/genshin_artifact_auxiliary#3]
希望适配下华为屏（2160*1440），谢谢大佬
![W%P3($3P332`2F(U5HN}MQM](https://user-images.githubusercontent.com/62316967/209996032-93089af0-0dcf-4633-944a-b1e8a8751786.png)

**Comment by SkeathyTomas** [comment]
> 希望适配下华为屏（2160*1440），谢谢大佬 ![W%P3($3P332`2F(U5HN}MQM](https://user-images.githubusercontent.com/62316967/209996032-93089af0-0dcf-4633-944a-b1e8a8751786.png)

请提供一下角色、背包两个页面全屏含标题栏的游戏窗口截图（如下图，并保证图片宽高2160*1440），上图这种非全屏窗口化模式太多了不考虑都兼容。
![](https://raw.githubusercontent.com/SkeathyTomas/img/main/img/20220929234442.png)

**Comment by Dr-Vibia** [comment]
![角色](https://user-images.githubusercontent.com/62316967/210035609-bb0bd1c0-6716-4d37-8802-2c1385d10927.png)
![背包](https://user-images.githubusercontent.com/62316967/210035611-9f2d7101-7db3-4cd5-a5fe-790e213cea51.png)
感谢您的回复，由于电脑性能差我一般在游戏界面都是采用的1920*1080，故之前窗口化截图有误。我现在已经截了2160*1440的窗口化界面给您参考。在此也仅提出一个小提议，是否可以增加一个手动选取OCR选框（快捷键）的功能，或许这样可以适配各种分辨率。

**Comment by SkeathyTomas** [comment]
> 感谢您的回复，由于电脑性能差我一般在游戏界面都是采用的1920_1080，故之前窗口化截图有误。我现在已经截了2160_1440的窗口化界面给您参考。在此也仅提出一个小提议，是否可以增加一个手动选取OCR选框（快捷键）的功能，或许这样可以适配各种分辨率。

看起来就算更新了分辨率适配也不能满足你窗口化游戏模式的需求，我先研究下怎么捕获游戏窗口坐标再做兼容处理。
至于后面的手动选取OCR区域，因为圣遗物、贴图坐标都受分辨率影响，光一个截图区域是不够的；另外把截图区域交给用户，也可能出现各种意想不到的识别解析错误，暂时不考虑了。

**Comment by Dr-Vibia** [comment]
我理解可能有些需求在代码层面上不好实现，我现阶段调整电脑分辨率后可以正常使用（但是每用一次就调一次比较麻烦）。如果您能适配我的分辨率最好不过，我也饱受这个分辨率的折磨很久了。最开始是在米游社看到您的项目，我会一直关注的，祝您能做出更好的作品，这么好的作品值得得到更多关注。

**Comment by SkeathyTomas** [comment]
> 我理解可能有些需求在代码层面上不好实现，我现阶段调整电脑分辨率后可以正常使用（但是每用一次就调一次比较麻烦）。如果您能适配我的分辨率最好不过，我也饱受这个分辨率的折磨很久了。最开始是在米游社看到您的项目，我会一直关注的，祝您能做出更好的作品，这么好的作品值得得到更多关注。

SkeathyTomas/genshin_artifact_auxiliary@a82a26d8f5b22cc9d14a9246c65085ca13784c8f 已经解决了窗口化（1920`*`1080）使用的兼容问题；全屏模式3:2的窗口下一个commit处理

**Comment by Dr-Vibia** [comment]
感谢 ：)
