### ISSUE TITLE
需求：云游戏窗口支持请求

### ISSUE THREAD

**Issue by hoixding** [SkeathyTomas/genshin_artifact_auxiliary#6]
需求描述：主要使用云游戏进行游戏，希望能在start云游戏平台上使用这个好用的工具
实现思路建议：1.增加对STGameOpt.exe（这个是start云游戏平台的游戏窗口，start.exe是平台的登录界面）的支持，而不仅仅是yuanshen.exe；
2.增加自定义窗口范围的支持，可以有效提高工具的鲁棒性（估计要改的代码会比较多）

**Comment by SkeathyTomas** [comment]
如果云游戏窗口布局都一样那兼容起来方便的。现在是通过窗口名称定位窗口和坐标的，不知云游戏的窗口名称叫什么?

**Comment by hoixding** [comment]
> 

不好意思，前段时间邮箱登录不上没及时回复。
窗口名称已经在上面提供，我可以再次提供
![image](https://user-images.githubusercontent.com/32367628/224111233-8199146a-47dc-4d65-8e59-562b7ae325e3.png)
如图，2号是具体的游戏窗口名称
详细的参数如下：（使用winspy抓取）
START云游戏-Game ( Class ) 
START Cloud Game Render ( ProcessName ) 
STGameOpt.exe ( ProcessPath )   
 ( Position ) 
Pos:  x160 y83  ▪  x²1759 y²982  ▪  Size:  w1600 h900
Client area size:  w1600 h900  ▪  left 0 top 0 right 0 bottom 0
布局如下：可以看出与客户端无明显差别
![image](https://user-images.githubusercontent.com/32367628/224113141-7119abf0-106e-4907-b6cf-ec0270f71829.png)

需要注意的是，start云游戏的各个游戏之间窗口名称无差别，这点建议放在readme中

**Comment by SkeathyTomas** [comment]
我自己实测了下窗口名称是这个，最新的commit已经能支持使用。不知你提供的窗口名称是语言版本不同还是其他，或者你可以看看最新的代码能不能跑。
![image](https://user-images.githubusercontent.com/22417231/225193043-c18f7209-05b5-4bc1-9646-ab695f168bb5.png)

对应的窗口识别是这一行：
`window_start = win32gui.FindWindow('START Cloud Game', 'START云游戏-Game')`

另外start的UI不是windows原生的，可能存在一些识别区域错位情况，我在窗口模式测试整体ok。

**Comment by hoixding** [comment]
感谢
